import { StyleSheet } from "react-native"
export const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    padding: 0,
    position: 'absolute',
    height: 54,
    left: 24,
    right: 24,
    top: 142,
  },
  newTask: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignContent: 'center',
    padding: 18,
    // gap: 4,
    width: 52,
    height: 52,
    backgroundColor: '#1E6F9F',
    borderRadius: 6,
  },
  buttonAddNewTask: {
    width: 56,
    height: 56,
    borderRadius: 5,
    backgroundColor: '#E23C44',
    alignItems: 'center',
    justifyContent: 'center',
  },
  input: {
    flex: 1,
    height: 56,
    backgroundColor: '#1F1E25',
    borderRadius: 6,
<<<<<<< HEAD
    color: '#262626',
=======
    color: '#fff',
>>>>>>> 5e94197 (feat: Finaliza input home empty)
    padding: 16,
    fontSize: 16,
    marginRight: 12,
    borderWidth: 1,
    borderTopColor: '#0D0D0D',
  },
  tasksContainer: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    padding: 0,
    // gap: 20,
    position: 'absolute',
    height: 247,
    left: 24,
    right: 24,
    top: 228,
  },
  taskStatus: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignContent: 'flex-end',
    padding: 0,
    // gap: 561,
    width: 327,
    height: 19,
    // order: 0,
    alignSelf: 'stretch',
    flexGrow: 0,
  },
  createdTask: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 0,
    // gap: 8,
    width: 87,
    height: 19,
    // order: 0,
    flexGrow: 0,
  },
  doneTask: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 0,
    // gap: 8,
    width: 111,
    height: 19,
    // order: 1,
    flexGrow: 0,
  },
  createdName: {
    width: 54,
    height: 17,
    // fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: "700",
    fontSize: 14,
    lineHeight: 17,
    color: '#4EA8DE',
    // order: 0,
    flexGrow: 0,
  },
  counterCreated: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 8,
    // gap: 100,
    width: 20,
    height: 19,
    backgroundColor: '#333',
    borderRadius: 100,
    // order: 1,
    flexGrow: 0,
  },
  counterStatus: {
    width: 9,
    height: 15,
    // fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: "700",
    fontSize: 12,
    lineHeight: 15,
    color: '#D9D9D9',
    // order: 0,
    flexGrow: 0,
  },
  doneName: {
    width: 78,
    height: 17,
    // fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: "700",
    fontSize: 14,
    lineHeight: 17,
    color: '#8284FA',
    // order: 0,
    flexGrow: 0,
  },
  empty: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    gap: 16,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 48,
    paddingBottom: 48,
    width: 327,
    height: 208,
    borderTopWidth: 1,
    borderTopColor: '#333',
    marginTop: 20,
  },
  emptyMessage: {
    width: 287,
    height: 40,
  },
  emptyText1: {
    // fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 14,
    lineHeight: 50,
    textAlign: 'center',
    color: '#808080',
    order: 1,
    alignSelf: 'stretch',
    flexGrow: 0,
  },
  emptyText2: {
    // fontFamily: 'Inter',
    fontStyle: 'normal',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
    color: '#808080',
    order: 1,
    alignSelf: 'stretch',
    flexGrow: 0,
  },
})